# Generated by Django 4.2.6 on 2023-10-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
