# Generated by Django 4.2.6 on 2023-10-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lecture_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecture',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnail'),
        ),
    ]
