# Generated by Django 4.2.6 on 2023-10-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_mycourses_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='preview',
        ),
    ]
