# Generated by Django 4.2.6 on 2023-10-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_lecture_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
