# Generated by Django 4.2.6 on 2023-10-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_profile_forget_password_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
